"""default value for Bookings.status is PENDING now

Revision ID: eabf10fe81c6
Revises: 1a35bcb4f90a
Create Date: 2024-08-30 15:45:30.773485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'eabf10fe81c6'
down_revision: Union[str, None] = '1a35bcb4f90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status', existing_type=sa.Integer(), nullable=False, server_default=text('5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'status', existing_type=sa.Integer(), nullable=False, server_default=None)
    # ### end Alembic commands ###
