"""Added new column in BookingConfirmations

Revision ID: 9cd055ff3f05
Revises: 462c40cc04f3
Create Date: 2024-08-16 21:17:39.179233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '9cd055ff3f05'
down_revision: Union[str, None] = '462c40cc04f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_confirmations', sa.Column('action', sa.Integer(), nullable=False, server_default=text('1')))
    # ### end Alembic commands ###

    # Обновляем существующие записи, чтобы установить значение по умолчанию для нового столбца
    op.execute("UPDATE booking_confirmations SET action = 0 WHERE action IS NULL")
    
    # Удаляем дефолтное значение с колонки
    op.alter_column('booking_confirmations', 'action', existing_type=sa.Integer(), nullable=False, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_confirmations', 'action')
    # ### end Alembic commands ###
