"""added booking_id column to BookingConfirmations

Revision ID: db03a326bc2f
Revises: 9a311cf95698
Create Date: 2024-08-19 20:04:19.675325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db03a326bc2f'
down_revision: Union[str, None] = '9a311cf95698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Применение значения по умолчанию
    op.add_column('booking_confirmations', sa.Column('booking_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'booking_confirmations', 'bookings', ['booking_id'], ['id'])

    # Удаление значения по умолчанию
    op.alter_column('booking_confirmations', 'booking_id', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_column('booking_confirmations', 'booking_id')
    # ### end Alembic commands ###
