name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: '2.11.0'  # Set the desired version of Docker Compose

      - name: Build and run tests
        run: |
          docker-compose build
          docker-compose up
      